# Generated by Django 4.2 on 2023-05-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('davlat', models.CharField(max_length=30)),
                ('logo', models.FileField(upload_to='')),
                ('prezident', models.CharField(blank=True, max_length=50)),
                ('murabbiy', models.CharField(blank=True, max_length=100)),
                ('yil', models.DateField()),
                ('eng_qimmat_sotuv', models.CharField(max_length=200)),
                ('eng_qimmat_tr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HozirgiMavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavsum', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('t_yil', models.DateField()),
                ('tr_narx', models.PositiveSmallIntegerField()),
                ('pozitsiya', models.CharField(max_length=150)),
                ('davlat', models.CharField(blank=True, max_length=150)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_nax', models.PositiveSmallIntegerField()),
                ('tahmn_narx', models.PositiveSmallIntegerField()),
                ('mavsum', models.CharField(max_length=6)),
                ('eski', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sotganlari', to='asosiy.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.player')),
                ('yangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.club')),
            ],
        ),
    ]
